name: Auto Merge test -> master

on:
  push:
    branches:
      - 'test/**'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessario para ter todo o historico e evitar erros de merge

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Merge test -> master
        run: |
          git fetch origin master
          git checkout master
          git merge origin/test/api --no-edit --allow-unrelated-histories
          git push origin master

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

