name: CI e Auto Merge test -> master

on:
  push:
    branches:
      - test/api

jobs:
  test_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # ajuste conforme sua versão

      - name: Cache de módulos Go
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Rodar testes
        run: go test ./... -v

      - name: Configurar Git
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge test -> master
        if: success()
        run: |
          git fetch origin master
          git checkout master
          git merge origin/test/api --no-edit --allow-unrelated-histories
          git push origin master

